=== oleggalimov/dbmonitoring/back/src/main/resources/json.schema/Response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "success": {
      "type": "boolean"
    },
    "body": {
      "type": "object"
    },
    "errors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string",
              "minLength": 1,
              "maxLength": 255
            },
            "title": {
              "type": "string",
              "minLength": 3,
              "maxLength": 255
            },
            "message": {
              "type": "string",
              "minLength": 3,
              "maxLength": 255
            }
          },
          "required": [
            "code",
            "title"
          ]
        }
      ]
    },
    "messages": {
      "type": "array",
      "additionalProperties": false,
      "items": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "code": {
              "type": "string",
              "minLength": 1,
              "maxLength": 255
            },
            "title": {
              "type": "string",
              "minLength": 3,
              "maxLength": 255
            },
            "message": {
              "type": "string",
              "minLength": 3,
              "maxLength": 255
            },
            "type": {
              "type": "string",
              "pattern": "[A-Z]",
              "minLength": 3,
              "maxLength": 255
            }
          },
          "required": [
            "code",
            "title",
            "type"
          ]
        }
      ]
    }
  },
  "required": [
    "success",
    "errors",
    "messages"
  ]
}

=== oleggalimov/dbmonitoring/front/src/test/json/list.json
{
  "success": true,
  "body": {
    "INSTANCES": [
      {
        "id": "1",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE"
      },
      {
        "id": "2",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE"
      },
      {
        "id": "3",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE"
      },
      {
        "id": "4",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE"
      },
      {
        "id": "5",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE"
      }
    ]
  },
  "errors": [],
  "messages": []
}

=== oleggalimov/dbmonitoring/front/src/test/json/WAIT_EVENT.json
{"success":true,"body":{"POINTS":[{"results":[{"series":[{"name":"WAIT_EVENT","tags":{"metric_name":"enq:_HW_-_contention"},"columns":["time","mean_value"],"values":[["2020-02-29T04:29:00Z",null],["2020-02-29T04:30:00Z",null],["2020-02-29T04:31:00Z",null],["2020-02-29T04:32:00Z",null],["2020-02-29T04:33:00Z",null],["2020-02-29T04:34:00Z",null],["2020-02-29T04:35:00Z",null],["2020-02-29T04:36:00Z",null],["2020-02-29T04:37:00Z",null],["2020-02-29T04:38:00Z",null],["2020-02-29T04:39:00Z",null],["2020-02-29T04:40:00Z",null],["2020-02-29T04:41:00Z",null],["2020-02-29T04:42:00Z",null],["2020-02-29T04:43:00Z",null],["2020-02-29T04:44:00Z",null],["2020-02-29T04:45:00Z",null],["2020-02-29T04:46:00Z",null],["2020-02-29T04:47:00Z",null],["2020-02-29T04:48:00Z",null],["2020-02-29T04:49:00Z",null],["2020-02-29T04:50:00Z",null],["2020-02-29T04:51:00Z",null],["2020-02-29T04:52:00Z",null],["2020-02-29T04:53:00Z",null],["2020-02-29T04:54:00Z",null],["2020-02-29T04:55:00Z",null],["2020-02-29T04:56:00Z",null],["2020-02-29T04:57:00Z",null],["2020-02-29T04:58:00Z",null],["2020-02-29T04:59:00Z",null],["2020-02-29T05:00:00Z",null],["2020-02-29T05:01:00Z",null],["2020-02-29T05:02:00Z",null],["2020-02-29T05:03:00Z",null],["2020-02-29T05:04:00Z",null],["2020-02-29T05:05:00Z",null],["2020-02-29T05:06:00Z",null],["2020-02-29T05:07:00Z",null],["2020-02-29T05:08:00Z",null],["2020-02-29T05:09:00Z",null],["2020-02-29T05:10:00Z",null],["2020-02-29T05:11:00Z",null],["2020-02-29T05:12:00Z",null],["2020-02-29T05:13:00Z",null],["2020-02-29T05:14:00Z",null],["2020-02-29T05:15:00Z",null],["2020-02-29T05:16:00Z",null],["2020-02-29T05:17:00Z",null],["2020-02-29T05:18:00Z",null],["2020-02-29T05:19:00Z",null],["2020-02-29T05:20:00Z",0.0],["2020-02-29T05:21:00Z",0.0],["2020-02-29T05:22:00Z",0.0],["2020-02-29T05:23:00Z",0.0],["2020-02-29T05:24:00Z",0.0],["2020-02-29T05:25:00Z",0.0],["2020-02-29T05:26:00Z",0.0],["2020-02-29T05:27:00Z",0.0],["2020-02-29T05:28:00Z",0.0],["2020-02-29T05:29:00Z",null]]}],"error":null}],"error":null}]},"errors":[],"messages":[]}

=== oleggalimov/dbmonitoring/front/src/test/json/statusList.json
{
  "success": true,
  "body": {
    "INSTANCES": [
      {
        "id": "test",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "?????? ?????/??????: The Network Adapter could not establish the connection"
      },
      {
        "id": "testOk",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "OK"
      },
      {
        "id": "test",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "?????? ?????/??????: The Network Adapter could not establish the connection"
      },
      {
        "id": "testOk",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "OK"
      },
      {
        "id": "test",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "?????? ?????/??????: The Network Adapter could not establish the connection"
      },
      {
        "id": "testOk",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "OK"
      },
      {
        "id": "test",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "?????? ?????/??????: The Network Adapter could not establish the connection"
      },
      {
        "id": "testOk",
        "host": "host",
        "port": 1520,
        "database": "testDataBase",
        "user": {
          "login": "login"
        },
        "type": "ORACLE",
        "status": "OK"
      }
    ]
  },
  "errors": [],
  "messages": []
}
